name: Run the build and tests, and create a pull request

on:
  # push:
  #   branches:
  #     - '*'
  #     - '!main'
  workflow_dispatch: # 手動トリガー
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Build"

      - name: Test
        run: echo "Test"

  create_pull_request:
    needs: [build_and_test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Git config
        run: git config push.autoSetupRemote true
      - name: Checkout Branch
        run: |
          BRANCH_NAME="openapi-generator_$(date +%Y%m%d_%H%M%S)"
          git checkout -b $BRANCH_NAME
      - name: Commit And Push
        run: |
          git config user.name ${{ secrets.MY_USER_NAME }}
          git config user.email ${{ secrets.MY_USER_EMAIL }}
          git commit --allow-empty -m "first commit"
          git push -u origin $BRANCH_NAME
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          gh pr create --base main --fill-first --assignee "@me"
