name: Run the build and tests, and create a pull request

on:
  # push:
  #   branches:
  #     - '*'
  #     - '!main'
  workflow_dispatch: # 手動トリガー
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Build"

      - name: Test
        run: echo "Test"

  create_pull_request:
    needs: [build_and_test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check and Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          gh pr create \
            -B main \
            -t "${{ github.event.head_commit.message }}" \
            -a "${{ github.actor }}"  \
            -F ./.github/workflows/PR_template.md
