name: openapi-generate-fe
on:
  workflow_dispatch: # 手動トリガー
  # pull_request:
  #   branches: [ main ]
  #   types: [ merged ]
jobs:
  generate-typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create a new branch
        run: |
          BRANCH_NAME="openapi-generator_$(date +%Y%m%d_%H%M%S)"
          git checkout -b $BRANCH_NAME
      - name: Install openapi-generator-cli
        run: npm install -g @openapitools/openapi-generator-cli
      - name: Generate TypeScript
        run: |
          openapi-generator-cli generate -i ./openapi.yaml -g typescript-axios -o ./generated
      - name: Commit changes
        run: |
          git config user.name ${{ secrets.MY_USER_NAME }}
          git config user.email ${{ secrets.MY_USER_EMAIL }}
          git add .
          git commit -m "Generate TypeScript from Swagger"
          git push --set-upstream origin $BRANCH_NAME
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: openapi-generator-${{ github.run_id }}
          title: "CI/CD + ${{ github.run_id }} - Generated TypeScript"
          body: "Generated TypeScript from Swagger"
          labels: "auto-generated"
          main-branch: main
