name: OpenapiGenerate FrontEnd
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    types: [ merged ]
  push:
    branches: [ main ]
jobs:
  generate-typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Git AutoSetupRemote True
        run: git config push.autoSetupRemote true
      - name: Create a new branch
        run: |
          BRANCH_NAME="openapi-generator_$(date +%Y%m%d_%H%M%S)"
          git checkout -b $BRANCH_NAME
      - name: Install openapi-generator-cli
        run: npm install -g @openapitools/openapi-generator-cli
      - name: Generate TypeScript
        run: |
          openapi-generator-cli generate -g typescript-axios -i ./ci-cd-swagger/openapi.yaml -o ./models --api-package api --model-package model --generate-alias-as-model --additional-properties withInterfaces=true --additional-properties withSeparateModelsAndApi=true
      - name: Commit changes
        run: |
          git config user.name ${{ secrets.MY_USER_NAME }}
          git config user.email ${{ secrets.MY_USER_EMAIL }}
          git add .
          git commit -m "Generate TypeScript from Swagger"
      - name: Git Push
        run: git push --set-upstream origin $BRANCH_NAME
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          gh pr create --base main --fill-first --assignee "@me"
